-- AlterTable
ALTER TABLE "bulk_sms_users" ALTER COLUMN "created" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "modified" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "participants" ADD COLUMN     "pcode" VARCHAR(100),
ALTER COLUMN "modified" SET DEFAULT CURRENT_TIMESTAMP;
